// All the different materials available
const MATERIAL_ANCIENT_AROWANA = 'Ancient Arowana';
const MATERIAL_APPLE = 'Apple';
const MATERIAL_ARMORANTH = 'Armoranth';
const MATERIAL_BLUE_NIGHTSHADE = 'Blue Nightshade';
const MATERIAL_BOMB_FLOWER = 'Bomb Flower';
const MATERIAL_BRIGHTCAP = 'Brightcap';
const MATERIAL_BRIGHT_EYED_CRAB = 'Bright-Eyed Crab';
const MATERIAL_CANE_SUGAR = 'Cane Sugar';
const MATERIAL_CHICKALOO_TREE_NUT = 'Chickaloo Tree Nut';
const MATERIAL_CHILLFIN_TROUT = 'Chillfin Trout';
const MATERIAL_CHILLSHROOM = 'Chillshroom';
const MATERIAL_COOL_SAFFLINA = 'Cool Safflina';
const MATERIAL_COURSER_BEE_HONEY = 'Courser Bee Honey';
const MATERIAL_DAZZLEFRUIT = 'Dazzlefruit';
const MATERIAL_DEEP_FIREFLY = 'Deep Firefly';
const MATERIAL_FIRE_FRUIT = 'Fire Fruit';
const MATERIAL_FLEET_LOTUS_SEEDS = 'Fleet-Lotus Seeds';
const MATERIAL_FORTIFIED_PUMPKIN = 'Fortified Pumpkin';
const MATERIAL_GLOWING_CAVE_FISH = 'Glowing Cave Fish';
const MATERIAL_GOAT_BUTTER = 'Goat Butter';
const MATERIAL_HIGHTAIL_LIZARD = 'Hightail Lizard';
const MATERIAL_HOT_FOOTED_FROG = 'Hot-Footed Frog';
const MATERIAL_HYLIAN_RICE = 'Hylian Rice';
const MATERIAL_HYRULE_HERB = 'Hyrule Herb';
const MATERIAL_ICE_FRUIT = 'Ice Fruit';
const MATERIAL_KOROK_FROND = 'Korok Frond';
const MATERIAL_MUDDLE_BUD = 'Muddle Bud';
const MATERIAL_OIL_JAR = 'Oil Jar';
const MATERIAL_PUFFSHROOM = 'Puffshroom';
const MATERIAL_RAW_MEAT = 'Raw Meat';
const MATERIAL_ROCK_SALT = 'Rock Salt';
const MATERIAL_SILENT_SHROOM = 'Silent Shroom';
const MATERIAL_SPLASH_FRUIT = 'Splash Fruit';
const MATERIAL_SPICY_PEPPER = 'Spicy Pepper';
const MATERIAL_STAMELLA_SHROOM = 'Stamella Shroom';
const MATERIAL_STAR_FRAGMENT = 'Star Fragment';
const MATERIAL_STICKY_FROG = 'Sticky Frog';
const MATERIAL_STICKY_LIZARD = 'Sticky Lizard';
const MATERIAL_SUNDELION = 'Sundelion';
const MATERIAL_SUNSET_FIREFLY = 'Sunset Firefly';
const MATERIAL_SUNSHROOM = 'Sunshroom';
const MATERIAL_SWIFT_VIOLET = 'Swift Violet';

// Matrix lookup
const MATRIX_LOOKUP = {};

// MATRIX_LOOKUP[] =
// MATRIX_LOOKUP[] =
// MATRIX_LOOKUP[] =
// MATRIX_LOOKUP[] =
// MATRIX_LOOKUP[] =
// MATRIX_LOOKUP[] =
// MATRIX_LOOKUP[] =
// MATRIX_LOOKUP[] =
// MATRIX_LOOKUP[] =
// MATRIX_LOOKUP[] =
// MATRIX_LOOKUP[] =
// MATRIX_LOOKUP[] =
